# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths-ignore:
      - "**/README.md"
    tags:
      - "*"
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: release apk
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.10.1"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: Millicom-MFS/AuthModule-Mobile
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/AuthModule-Mobile
      - run: |
            ls ./.github/actions/AuthModule-Mobile
      - uses: actions/checkout@v2
      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY_AUTH0 }}
      #     known_hosts: github.com
      #     name: id_rsa-auth0
      #     config: |
      #       Host github.com
      #       HostName github.com
      #       User git
      #       IdentityFile ~/.ssh/id_rsa-auth0
      # - name: Setup SSH
      #   uses: MrSquaare/ssh-setup-action@v1
      #   with:
      #     host: github.com
      #     private-key: ${{ secrets.SSH_PRIVATE_KEY_AUTH0 }}
      # - name: Clone repository
      #   run: git clone git@github.com:Millicom-MFS/AuthModule-Mobile.git
      # - name: Setup SSH Keys and known_hosts
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   run: |
      #       ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      #       ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      # - name: Some task that fetches dependencies
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   run: ./fetch-deps.sh
      - name: Setup SSH passphrase
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            echo '#!/bin/sh' > ~/.ssh_askpass
            echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null
            # - name: Some task that fetches dependencies

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.1"
      - run: |
            ls -al
            pwd
            ls ./.***/actions/AuthModule-Mobile
            cd ./.***/actions
            ls -al
      # - run: flutter pub get
      # - run: flutter analyze
      # - run: flutter test
      # - run: flutter build apk --release
      
      #- run: flutter build appbundle

      # - name: Create a Release APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release-apk
      #     path: build/app/outputs/apk/release/app-release.apk

        #uses: ncipollo/release-action@v1
        #with:
        #artifacts: "build/app/outputs/apk/release/*.apk"
        #token: ${{ secrets.TOKEN }}
        #tag: v1.0.${{ github.run_number }}